package com.BaGulBaGul.BaGulBaGul.domain.user.alarm.constant;

public enum AlarmType {
    NEW_EVENT_LIKE,
    NEW_EVENT_COMMENT,
    NEW_EVENT_COMMENT_LIKE,
    NEW_EVENT_COMMENT_CHILD,
    NEW_EVENT_COMMENT_CHILD_LIKE,
    NEW_RECRUITMENT_LIKE,
    NEW_RECRUITMENT_COMMENT,
    NEW_RECRUITMENT_COMMENT_LIKE,
    NEW_RECRUITMENT_COMMENT_CHILD,
    NEW_RECRUITMENT_COMMENT_CHILD_LIKE
}
