spring:
  config:
    activate:
      on-profile: 'upload-aws'
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_S3_REGION}
      auto: false
    stack:
      auto: false
resource:
  temp:
    effective-minute: ${TEMP_RESOURCE_EFFECTIVE_MINUTE}
    batch:
      scheduler:
        cron: ${CLEAR_TEMP_RESOURCE_JOB_SCHEDULER_CRON}
