ALTER TABLE event_category DROP FOREIGN KEY FK__EVENT_CATEGORY__CATEGORY_ID;

ALTER TABLE event_category
ADD CONSTRAINT FK__EVENT_CATEGORY__CATEGORY_ID
FOREIGN KEY (category_id)
REFERENCES category(category_id)
ON DELETE CASCADE;
